### ISSUE TITLE
Remove the reference to a `selected protocol` inside the `sink`-description

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/CarrierBillingCheckOut#168]
**Problem description**
For sure based on Commonalities you normally can also use a `protocol`-property.
This property is not used in CarrierBilling (for now).
So I guess this reference can be removed.

```yaml
        sink:
          type: string
          format: url
          description: The address to which events shall be delivered using the selected protocol.
          example: "https://endpoint.example.com/sink"
```

**Expected behavior**

```yaml
        sink:
          type: string
          format: url
          description: The address to which events shall be delivered.
          example: "https://endpoint.example.com/sink"
```

**Comment by hdamker** [comment]
@maxl2287 Good catch ... root cause might be that Commonalities is not listing the `protocol` property within the guidelines for implicit subscriptions. 

Within qod-provisioning.yaml we changed it last minute before the r1.1 to:

```
        sink:
          type: string
          format: url
          description: The address to which events shall be delivered, using the HTTP protocol.
          example: "https://endpoint.example.com/sink"
```
