### ISSUE TITLE
Should the Generic401 code value be "UNAUTHENTICATED" instead of "UNAUTHORIZED" 

### ISSUE THREAD

**Issue by trehman-gsma** [camaraproject/CarrierBillingCheckOut#173]
**Problem description**
In the [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/r0.4.0-rc.2/artifacts/CAMARA_common.yaml#L173), the 401 code is `UNAUTHENTICATED`:
```
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials.
```

However in [carrier_billing.yaml](https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing.yaml#L1596) and [carrier_billing_refund.yaml](https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing_refund.yaml#L1033), the code is `UNAUTHORIZED`:
```
          example:
            code: UNAUTHORIZED
            status: 401
            message: "Authorization failed: ..."
```

Should the value be aligned with [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/r0.4.0-rc.2/artifacts/CAMARA_common.yaml#L173)? I believe many other CAMARA APIs are also using `UNAUTHENTICATED`.

**Expected behavior**
The `code` value to be changed in [carrier_billing.yaml](https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing.yaml#L1596) and [carrier_billing_refund.yaml](https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing_refund.yaml#L1033) to align with [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/r0.4.0-rc.2/artifacts/CAMARA_common.yaml#L173)
